language: python
python:
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install argparse"
install: python scc.py
script: nosetests test
