language: python
python:
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r dev_requirements.txt --use-mirrors"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
install:
  - python setup.py sdist install
  - scc -h
script:
  - flake8 scc test
  - nosetests -v -d test/unit
